version: '3.1'

services:
  # nginx: 
  #   container_name: nginx
  #   restart: always
  #   build:
  #     context: ./client
  #     target: ${NODE_ENV}
  #   ports:
  #     - 8080:80


  node: 
    container_name: node
    restart: always
    build: 
      context: .
      target: ${NODE_ENV}
      args:
        PORT: ${PORT}
    
    ports:
      - 5000:${PORT}
    volumes:
      - ./nodeData:/usr/src/app/data/
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - mongo


  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes: 
      - ./mongodbData:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    ports:
      - 27016:27017

