version: '3.8'

services:
  nginx: 
    container_name: nginx
    build:
      context: ./client
    ports:
      - 80:80
      - 443:443

    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email sportsveins@gmail.com -d sportsveins.com --agree-tos

  node: 
    container_name: node
    restart: always
    build: 
      context: .
      target: ${NODE_ENV}
      args:
        PORT: ${PORT}
    
    ports:
      - 5000:${PORT}
    volumes:
      - ./nodeData:/usr/src/app/data/
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - mongo


  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes: 
      - ./mongodbData:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    ports:
      - 27016:27017

