version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes: 
      - ./docker_data/db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27016:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on: 
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD:  ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/