export const LANDING_SIDEBAR_TOGGLE = "LANDING_SIDEBAR_TOGGLE";
export const SELECT_TEMPLATE = "SELECT_TEMPLATE";

// CART REDUCER
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const SET_CART_SIZE = "SET_CART_SIZE";

// USER
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";
