export const LANDING_SIDEBAR_TOGGLE = "LANDING_SIDEBAR_TOGGLE";
export const SELECT_TEMPLATE = "SELECT_TEMPLATE";

// CART REDUCER
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const SET_CART_SIZE = "SET_CART_SIZE";

// USER
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

export const TYPES_LOAD = "TYPES_LOAD";
export const TYPES_LOAD_ERROR = "TYPES_LOAD_ERROR";
export const TYPES_DELETE = "TYPES_DELETE";
export const TYPES_DELETE_ERROR = "TYPES_DELETE_ERROR";
export const TYPES_EDIT = "TYPES_EDIT";
export const TYPES_EDIT_ERROR = "TYPES_EDIT_ERROR";

export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";
export const CATEGORY_LOAD = "CATEGORY_LOAD";
export const CATEGORY_LOAD_ERROR = "CATEGORY_LOAD_ERROR";
export const CATEGORY_DELETE = "CATEGORY_DELETE";
export const CATEGORY_DELETE_ERROR = "CATEGORY_DELETE_ERROR";
export const CATEGORY_EDIT = "CATEGORY_EDIT";
export const CATEGORY_EDIT_ERROR = "CATEGORY_EDIT_ERROR";

export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS_ERROR = "GET_PRODUCT_DETAILS_ERROR";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_ERRROR = "EDIT_PRODUCT_ERRROR";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_ERRROR = "DELETE_PRODUCT_ERRROR";

export const GET_LANDING_LIST = "GET_LANDING_LIST";
export const DISCOVER_ALL = "DISCOVER_ALL";
export const DISCOVER_FEATURED = "DISCOVER_FEATURED";
export const DISCOVER_POPULAR = "DISCOVER_POPULAR";
export const DISCOVER_ERROR = "DISCOVER_ERROR";
export const DISCOVER_LOAD = "DISCOVER_LOAD";
export const PRODUCT_BY_CATEGORY = "PRODUCT_BY_CATEGORY";
