const colors = [
  { name: "Red", hex: " #d80009" },
  { name: "Orange", hex: " #ff5e00" },
  { name: "White", hex: " #ffffff" },
  { name: "Black", hex: " #000000" },
  { name: "Royal Blue", hex: " #012aff" },
  { name: "Purple", hex: " #6f00bd" },
  { name: "Teal", hex: " #018d8d" },
  { name: "Silver", hex: " #ababab" },
  { name: "Sport Yellow", hex: " #fac11a" },
  { name: "Maroon", hex: " #5a1125" },
  { name: "Pink", hex: " #ea4d92" },
  { name: "Magenta", hex: " #c0208c" },
  { name: "Lime", hex: " #78d200" },
  { name: "Navy", hex: " #16224c" },
  { name: "Light Pink", hex: " #ffadd3" },
  { name: "Dark Gray", hex: " #3d3f3f" },
  { name: "Yellow", hex: " #ffea00" },
  { name: "Neon Yellow", hex: " #eaff00" },
  { name: "Neon Green", hex: "#aeff00 " },
  { name: "Gold", hex: " #b39952" },
  { name: "Brown", hex: " #654321" },
  { name: "Green", hex: " #5aa601" },
  { name: "Crimson", hex: " #841313" },
  { name: "Light Blue", hex: " #3cabf7" },
  { name: "Dark Green", hex: " #034501" },
];

export default colors;
